//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cryptokey
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public string cryptone { get; set; }
        public string crypttwo { get; set; }
        public string crypttree { get; set; }
    
        public virtual User User { get; set; }
    }
}
